<?php
	$regions = [
		["id"=>001, "parent"=>229, "text"=>"ALABAMA", "value"=>"AL"],
		["id"=>002, "parent"=>229, "text"=>"ALASKA", "value"=>"AK"],
		["id"=>003, "parent"=>229, "text"=>"AMERICAN SAMOA", "value"=>"AS"],
		["id"=>004, "parent"=>229, "text"=>"ARIZONA", "value"=>"AZ"],
		["id"=>005, "parent"=>229, "text"=>"ARKANSAS", "value"=>"AR"],
		["id"=>006, "parent"=>229, "text"=>"CALIFORNIA", "value"=>"CA"],
		["id"=>007, "parent"=>229, "text"=>"COLORADO", "value"=>"CO"],
		["id"=>008, "parent"=>229, "text"=>"CONNECTICUT", "value"=>"CT"],
		["id"=>009, "parent"=>229, "text"=>"DELAWARE", "value"=>"DE"],
		["id"=>010, "parent"=>229, "text"=>"DISTRICT OF COLUMBIA", "value"=>"DC"],
		["id"=>011, "parent"=>229, "text"=>"FEDERATED STATES OF MICRONESIA", "value"=>"FM"],
		["id"=>012, "parent"=>229, "text"=>"FLORIDA", "value"=>"FL"],
		["id"=>013, "parent"=>229, "text"=>"GEORGIA", "value"=>"GA"],
		["id"=>014, "parent"=>229, "text"=>"GUAM", "value"=>"GU"],
		["id"=>015, "parent"=>229, "text"=>"HAWAII", "value"=>"HI"],
		["id"=>016, "parent"=>229, "text"=>"IDAHO", "value"=>"ID"],
		["id"=>017, "parent"=>229, "text"=>"ILLINOIS", "value"=>"IL"],
		["id"=>018, "parent"=>229, "text"=>"INDIANA", "value"=>"IN"],
		["id"=>019, "parent"=>229, "text"=>"IOWA", "value"=>"IA"],
		["id"=>020, "parent"=>229, "text"=>"KANSAS", "value"=>"KS"],
		["id"=>021, "parent"=>229, "text"=>"KENTUCKY", "value"=>"KY"],
		["id"=>022, "parent"=>229, "text"=>"LOUISIANA", "value"=>"LA"],
		["id"=>023, "parent"=>229, "text"=>"MAINE", "value"=>"ME"],
		["id"=>024, "parent"=>229, "text"=>"MARSHALL ISLANDS", "value"=>"MH"],
		["id"=>025, "parent"=>229, "text"=>"MARYLAND", "value"=>"MD"],
		["id"=>026, "parent"=>229, "text"=>"MASSACHUSETTS", "value"=>"MA"],
		["id"=>027, "parent"=>229, "text"=>"MICHIGAN", "value"=>"MI"],
		["id"=>028, "parent"=>229, "text"=>"MINNESOTA", "value"=>"MN"],
		["id"=>029, "parent"=>229, "text"=>"MISSISSIPPI", "value"=>"MS"],
		["id"=>030, "parent"=>229, "text"=>"MISSOURI", "value"=>"MO"],
		["id"=>031, "parent"=>229, "text"=>"MONTANA", "value"=>"MT"],
		["id"=>032, "parent"=>229, "text"=>"NEBRASKA", "value"=>"NE"],
		["id"=>033, "parent"=>229, "text"=>"NEVADA", "value"=>"NV"],
		["id"=>034, "parent"=>229, "text"=>"NEW HAMPSHIRE", "value"=>"NH"],
		["id"=>035, "parent"=>229, "text"=>"NEW JERSEY", "value"=>"NJ"],
		["id"=>036, "parent"=>229, "text"=>"NEW MEXICO", "value"=>"NM"],
		["id"=>037, "parent"=>229, "text"=>"NEW YORK", "value"=>"NY"],
		["id"=>038, "parent"=>229, "text"=>"NORTH CAROLINA", "value"=>"NC"],
		["id"=>039, "parent"=>229, "text"=>"NORTH DAKOTA", "value"=>"ND"],
		["id"=>040, "parent"=>229, "text"=>"NORTHERN MARIANA ISLANDS", "value"=>"MP"],
		["id"=>041, "parent"=>229, "text"=>"OHIO", "value"=>"OH"],
		["id"=>042, "parent"=>229, "text"=>"OKLAHOMA", "value"=>"OK"],
		["id"=>043, "parent"=>229, "text"=>"OREGON", "value"=>"OR"],
		["id"=>044, "parent"=>229, "text"=>"PALAU", "value"=>"PW"],
		["id"=>045, "parent"=>229, "text"=>"PENNSYLVANIA", "value"=>"PA"],
		["id"=>046, "parent"=>229, "text"=>"PUERTO RICO", "value"=>"PR"],
		["id"=>047, "parent"=>229, "text"=>"RHODE ISLAND", "value"=>"RI"],
		["id"=>048, "parent"=>229, "text"=>"SOUTH CAROLINA", "value"=>"SC"],
		["id"=>049, "parent"=>229, "text"=>"SOUTH DAKOTA", "value"=>"SD"],
		["id"=>050, "parent"=>229, "text"=>"TENNESSEE", "value"=>"TN"],
		["id"=>051, "parent"=>229, "text"=>"TEXAS", "value"=>"TX"],
		["id"=>052, "parent"=>229, "text"=>"UTAH", "value"=>"UT"],
		["id"=>053, "parent"=>229, "text"=>"VERMONT", "value"=>"VT"],
		["id"=>054, "parent"=>229, "text"=>"VIRGIN ISLANDS", "value"=>"VI"],
		["id"=>055, "parent"=>229, "text"=>"VIRGINIA", "value"=>"VA"],
		["id"=>056, "parent"=>229, "text"=>"WASHINGTON", "value"=>"WA"],
		["id"=>057, "parent"=>229, "text"=>"WEST VIRGINIA", "value"=>"WV"],
		["id"=>058, "parent"=>229, "text"=>"WISCONSIN", "value"=>"WI"],
		["id"=>059, "parent"=>229, "text"=>"WYOMING", "value"=>"WY" ],
		["id"=>060, "parent"=>038, "text"=>"Alberta", "value"=>"AB"],
		["id"=>061, "parent"=>038, "text"=>"British Columbia", "value"=>"BC"],
		["id"=>062, "parent"=>038, "text"=>"Manitoba", "value"=>"MB"],
		["id"=>063, "parent"=>038, "text"=>"New Brunswick", "value"=>"NB"],
		["id"=>064, "parent"=>038, "text"=>"Newfoundland", "value"=>"NL"],
		["id"=>065, "parent"=>038, "text"=>"Northwest Territories", "value"=>"NT"],
		["id"=>066, "parent"=>038, "text"=>"Nova Scotia", "value"=>"NS"],
		["id"=>067, "parent"=>038, "text"=>"Nunavut", "value"=>"NU"],
		["id"=>068, "parent"=>038, "text"=>"Ontario", "value"=>"ON"],
		["id"=>069, "parent"=>038, "text"=>"Prince Edward Island", "value"=>"PE"],
		["id"=>070, "parent"=>038, "text"=>"Quebec", "value"=>"QC"],
		["id"=>071, "parent"=>038, "text"=>"Saskatchewan", "value"=>"SK"],
		["id"=>072, "parent"=>038, "text"=>"Yukon Territory", "value"=>"YT"]
	];

	header("Content-Type: application/json");
	echo json_encode($regions);
//print_r( $regions );
