<?php
	$countries = [
		["id"=>000, "text"=>"Afghanistan", "value"=>"AF"],
		["id"=>001, "text"=>"Åland Islands", "value"=>"AX"],
		["id"=>002, "text"=>"Albania", "value"=>"AL"],
		["id"=>003, "text"=>"Algeria", "value"=>"DZ"],
		["id"=>004, "text"=>"American Samoa", "value"=>"AS"],
		["id"=>005, "text"=>"AndorrA", "value"=>"AD"],
		["id"=>006, "text"=>"Angola", "value"=>"AO"],
		["id"=>007, "text"=>"Anguilla", "value"=>"AI"],
		["id"=>008, "text"=>"Antarctica", "value"=>"AQ"],
		["id"=>009, "text"=>"Antigua and Barbuda", "value"=>"AG"],
		["id"=>010, "text"=>"Argentina", "value"=>"AR"],
		["id"=>011, "text"=>"Armenia", "value"=>"AM"],
		["id"=>012, "text"=>"Aruba", "value"=>"AW"],
		["id"=>013, "text"=>"Australia", "value"=>"AU"],
		["id"=>014, "text"=>"Austria", "value"=>"AT"],
		["id"=>015, "text"=>"Azerbaijan", "value"=>"AZ"],
		["id"=>016, "text"=>"Bahamas", "value"=>"BS"],
		["id"=>017, "text"=>"Bahrain", "value"=>"BH"],
		["id"=>018, "text"=>"Bangladesh", "value"=>"BD"],
		["id"=>019, "text"=>"Barbados", "value"=>"BB"],
		["id"=>020, "text"=>"Belarus", "value"=>"BY"],
		["id"=>021, "text"=>"Belgium", "value"=>"BE"],
		["id"=>022, "text"=>"Belize", "value"=>"BZ"],
		["id"=>023, "text"=>"Benin", "value"=>"BJ"],
		["id"=>024, "text"=>"Bermuda", "value"=>"BM"],
		["id"=>025, "text"=>"Bhutan", "value"=>"BT"],
		["id"=>026, "text"=>"Bolivia", "value"=>"BO"],
		["id"=>027, "text"=>"Bosnia and Herzegovina", "value"=>"BA"],
		["id"=>028, "text"=>"Botswana", "value"=>"BW"],
		["id"=>029, "text"=>"Bouvet Island", "value"=>"BV"],
		["id"=>030, "text"=>"Brazil", "value"=>"BR"],
		["id"=>031, "text"=>"British Indian Ocean Territory", "value"=>"IO"],
		["id"=>032, "text"=>"Brunei Darussalam", "value"=>"BN"],
		["id"=>033, "text"=>"Bulgaria", "value"=>"BG"],
		["id"=>034, "text"=>"Burkina Faso", "value"=>"BF"],
		["id"=>035, "text"=>"Burundi", "value"=>"BI"],
		["id"=>036, "text"=>"Cambodia", "value"=>"KH"],
		["id"=>037, "text"=>"Cameroon", "value"=>"CM"],
		["id"=>038, "text"=>"Canada", "value"=>"CA"],
		["id"=>039, "text"=>"Cape Verde", "value"=>"CV"],
		["id"=>040, "text"=>"Cayman Islands", "value"=>"KY"],
		["id"=>041, "text"=>"Central African Republic", "value"=>"CF"],
		["id"=>042, "text"=>"Chad", "value"=>"TD"],
		["id"=>043, "text"=>"Chile", "value"=>"CL"],
		["id"=>044, "text"=>"China", "value"=>"CN"],
		["id"=>045, "text"=>"Christmas Island", "value"=>"CX"],
		["id"=>046, "text"=>"Cocos (Keeling) Islands", "value"=>"CC"],
		["id"=>047, "text"=>"Colombia", "value"=>"CO"],
		["id"=>048, "text"=>"Comoros", "value"=>"KM"],
		["id"=>049, "text"=>"Congo", "value"=>"CG"],
		["id"=>050, "text"=>"Congo, The Democratic Republic of the", "value"=>"CD"],
		["id"=>051, "text"=>"Cook Islands", "value"=>"CK"],
		["id"=>052, "text"=>"Costa Rica", "value"=>"CR"],
		["id"=>053, "text"=>"Cote D\"Ivoire", "value"=>"CI"],
		["id"=>054, "text"=>"Croatia", "value"=>"HR"],
		["id"=>055, "text"=>"Cuba", "value"=>"CU"],
		["id"=>056, "text"=>"Cyprus", "value"=>"CY"],
		["id"=>057, "text"=>"Czech Republic", "value"=>"CZ"],
		["id"=>058, "text"=>"Denmark", "value"=>"DK"],
		["id"=>059, "text"=>"Djibouti", "value"=>"DJ"],
		["id"=>060, "text"=>"Dominica", "value"=>"DM"],
		["id"=>061, "text"=>"Dominican Republic", "value"=>"DO"],
		["id"=>062, "text"=>"Ecuador", "value"=>"EC"],
		["id"=>063, "text"=>"Egypt", "value"=>"EG"],
		["id"=>064, "text"=>"El Salvador", "value"=>"SV"],
		["id"=>065, "text"=>"Equatorial Guinea", "value"=>"GQ"],
		["id"=>066, "text"=>"Eritrea", "value"=>"ER"],
		["id"=>067, "text"=>"Estonia", "value"=>"EE"],
		["id"=>068, "text"=>"Ethiopia", "value"=>"ET"],
		["id"=>069, "text"=>"Falkland Islands (Malvinas)", "value"=>"FK"],
		["id"=>070, "text"=>"Faroe Islands", "value"=>"FO"],
		["id"=>071, "text"=>"Fiji", "value"=>"FJ"],
		["id"=>072, "text"=>"Finland", "value"=>"FI"],
		["id"=>073, "text"=>"France", "value"=>"FR"],
		["id"=>074, "text"=>"French Guiana", "value"=>"GF"],
		["id"=>075, "text"=>"French Polynesia", "value"=>"PF"],
		["id"=>076, "text"=>"French Southern Territories", "value"=>"TF"],
		["id"=>077, "text"=>"Gabon", "value"=>"GA"],
		["id"=>078, "text"=>"Gambia", "value"=>"GM"],
		["id"=>079, "text"=>"Georgia", "value"=>"GE"],
		["id"=>080, "text"=>"Germany", "value"=>"DE"],
		["id"=>081, "text"=>"Ghana", "value"=>"GH"],
		["id"=>082, "text"=>"Gibraltar", "value"=>"GI"],
		["id"=>083, "text"=>"Greece", "value"=>"GR"],
		["id"=>084, "text"=>"Greenland", "value"=>"GL"],
		["id"=>085, "text"=>"Grenada", "value"=>"GD"],
		["id"=>086, "text"=>"Guadeloupe", "value"=>"GP"],
		["id"=>087, "text"=>"Guam", "value"=>"GU"],
		["id"=>088, "text"=>"Guatemala", "value"=>"GT"],
		["id"=>089, "text"=>"Guernsey", "value"=>"GG"],
		["id"=>090, "text"=>"Guinea", "value"=>"GN"],
		["id"=>091, "text"=>"Guinea-Bissau", "value"=>"GW"],
		["id"=>092, "text"=>"Guyana", "value"=>"GY"],
		["id"=>093, "text"=>"Haiti", "value"=>"HT"],
		["id"=>094, "text"=>"Heard Island and Mcdonald Islands", "value"=>"HM"],
		["id"=>095, "text"=>"Holy See (Vatican City State)", "value"=>"VA"],
		["id"=>096, "text"=>"Honduras", "value"=>"HN"],
		["id"=>097, "text"=>"Hong Kong", "value"=>"HK"],
		["id"=>098, "text"=>"Hungary", "value"=>"HU"],
		["id"=>099, "text"=>"Iceland", "value"=>"IS"],
		["id"=>100, "text"=>"India", "value"=>"IN"],
		["id"=>101, "text"=>"Indonesia", "value"=>"ID"],
		["id"=>102, "text"=>"Iran, Islamic Republic Of", "value"=>"IR"],
		["id"=>103, "text"=>"Iraq", "value"=>"IQ"],
		["id"=>104, "text"=>"Ireland", "value"=>"IE"],
		["id"=>105, "text"=>"Isle of Man", "value"=>"IM"],
		["id"=>106, "text"=>"Israel", "value"=>"IL"],
		["id"=>107, "text"=>"Italy", "value"=>"IT"],
		["id"=>108, "text"=>"Jamaica", "value"=>"JM"],
		["id"=>109, "text"=>"Japan", "value"=>"JP"],
		["id"=>110, "text"=>"Jersey", "value"=>"JE"],
		["id"=>111, "text"=>"Jordan", "value"=>"JO"],
		["id"=>112, "text"=>"Kazakhstan", "value"=>"KZ"],
		["id"=>113, "text"=>"Kenya", "value"=>"KE"],
		["id"=>114, "text"=>"Kiribati", "value"=>"KI"],
		["id"=>115, "text"=>"Korea, Democratic People\"S Republic of", "value"=>"KP"],
		["id"=>116, "text"=>"Korea, Republic of", "value"=>"KR"],
		["id"=>117, "text"=>"Kuwait", "value"=>"KW"],
		["id"=>118, "text"=>"Kyrgyzstan", "value"=>"KG"],
		["id"=>119, "text"=>"Lao People\"S Democratic Republic", "value"=>"LA"],
		["id"=>120, "text"=>"Latvia", "value"=>"LV"],
		["id"=>121, "text"=>"Lebanon", "value"=>"LB"],
		["id"=>122, "text"=>"Lesotho", "value"=>"LS"],
		["id"=>123, "text"=>"Liberia", "value"=>"LR"],
		["id"=>124, "text"=>"Libyan Arab Jamahiriya", "value"=>"LY"],
		["id"=>125, "text"=>"Liechtenstein", "value"=>"LI"],
		["id"=>126, "text"=>"Lithuania", "value"=>"LT"],
		["id"=>127, "text"=>"Luxembourg", "value"=>"LU"],
		["id"=>128, "text"=>"Macao", "value"=>"MO"],
		["id"=>129, "text"=>"Macedonia, The Former Yugoslav Republic of", "value"=>"MK"],
		["id"=>130, "text"=>"Madagascar", "value"=>"MG"],
		["id"=>131, "text"=>"Malawi", "value"=>"MW"],
		["id"=>132, "text"=>"Malaysia", "value"=>"MY"],
		["id"=>133, "text"=>"Maldives", "value"=>"MV"],
		["id"=>134, "text"=>"Mali", "value"=>"ML"],
		["id"=>135, "text"=>"Malta", "value"=>"MT"],
		["id"=>136, "text"=>"Marshall Islands", "value"=>"MH"],
		["id"=>137, "text"=>"Martinique", "value"=>"MQ"],
		["id"=>138, "text"=>"Mauritania", "value"=>"MR"],
		["id"=>139, "text"=>"Mauritius", "value"=>"MU"],
		["id"=>140, "text"=>"Mayotte", "value"=>"YT"],
		["id"=>141, "text"=>"Mexico", "value"=>"MX"],
		["id"=>142, "text"=>"Micronesia, Federated States of", "value"=>"FM"],
		["id"=>143, "text"=>"Moldova, Republic of", "value"=>"MD"],
		["id"=>144, "text"=>"Monaco", "value"=>"MC"],
		["id"=>145, "text"=>"Mongolia", "value"=>"MN"],
		["id"=>146, "text"=>"Montserrat", "value"=>"MS"],
		["id"=>147, "text"=>"Morocco", "value"=>"MA"],
		["id"=>148, "text"=>"Mozambique", "value"=>"MZ"],
		["id"=>149, "text"=>"Myanmar", "value"=>"MM"],
		["id"=>150, "text"=>"Namibia", "value"=>"NA"],
		["id"=>151, "text"=>"Nauru", "value"=>"NR"],
		["id"=>152, "text"=>"Nepal", "value"=>"NP"],
		["id"=>153, "text"=>"Netherlands", "value"=>"NL"],
		["id"=>154, "text"=>"Netherlands Antilles", "value"=>"AN"],
		["id"=>155, "text"=>"New Caledonia", "value"=>"NC"],
		["id"=>156, "text"=>"New Zealand", "value"=>"NZ"],
		["id"=>157, "text"=>"Nicaragua", "value"=>"NI"],
		["id"=>158, "text"=>"Niger", "value"=>"NE"],
		["id"=>159, "text"=>"Nigeria", "value"=>"NG"],
		["id"=>160, "text"=>"Niue", "value"=>"NU"],
		["id"=>161, "text"=>"Norfolk Island", "value"=>"NF"],
		["id"=>162, "text"=>"Northern Mariana Islands", "value"=>"MP"],
		["id"=>163, "text"=>"Norway", "value"=>"NO"],
		["id"=>164, "text"=>"Oman", "value"=>"OM"],
		["id"=>165, "text"=>"Pakistan", "value"=>"PK"],
		["id"=>166, "text"=>"Palau", "value"=>"PW"],
		["id"=>167, "text"=>"Palestinian Territory, Occupied", "value"=>"PS"],
		["id"=>168, "text"=>"Panama", "value"=>"PA"],
		["id"=>168, "text"=>"Papua New Guinea", "value"=>"PG"],
		["id"=>170, "text"=>"Paraguay", "value"=>"PY"],
		["id"=>171, "text"=>"Peru", "value"=>"PE"],
		["id"=>172, "text"=>"Philippines", "value"=>"PH"],
		["id"=>173, "text"=>"Pitcairn", "value"=>"PN"],
		["id"=>174, "text"=>"Poland", "value"=>"PL"],
		["id"=>175, "text"=>"Portugal", "value"=>"PT"],
		["id"=>176, "text"=>"Puerto Rico", "value"=>"PR"],
		["id"=>177, "text"=>"Qatar", "value"=>"QA"],
		["id"=>178, "text"=>"Reunion", "value"=>"RE"],
		["id"=>179, "text"=>"Romania", "value"=>"RO"],
		["id"=>180, "text"=>"Russian Federation", "value"=>"RU"],
		["id"=>181, "text"=>"RWANDA", "value"=>"RW"],
		["id"=>182, "text"=>"Saint Helena", "value"=>"SH"],
		["id"=>183, "text"=>"Saint Kitts and Nevis", "value"=>"KN"],
		["id"=>184, "text"=>"Saint Lucia", "value"=>"LC"],
		["id"=>185, "text"=>"Saint Pierre and Miquelon", "value"=>"PM"],
		["id"=>186, "text"=>"Saint Vincent and the Grenadines", "value"=>"VC"],
		["id"=>187, "text"=>"Samoa", "value"=>"WS"],
		["id"=>188, "text"=>"San Marino", "value"=>"SM"],
		["id"=>189, "text"=>"Sao Tome and Principe", "value"=>"ST"],
		["id"=>190, "text"=>"Saudi Arabia", "value"=>"SA"],
		["id"=>191, "text"=>"Senegal", "value"=>"SN"],
		["id"=>192, "text"=>"Serbia and Montenegro", "value"=>"CS"],
		["id"=>193, "text"=>"Seychelles", "value"=>"SC"],
		["id"=>194, "text"=>"Sierra Leone", "value"=>"SL"],
		["id"=>195, "text"=>"Singapore", "value"=>"SG"],
		["id"=>196, "text"=>"Slovakia", "value"=>"SK"],
		["id"=>197, "text"=>"Slovenia", "value"=>"SI"],
		["id"=>198, "text"=>"Solomon Islands", "value"=>"SB"],
		["id"=>199, "text"=>"Somalia", "value"=>"SO"],
		["id"=>200, "text"=>"South Africa", "value"=>"ZA"],
		["id"=>201, "text"=>"South Georgia and the South Sandwich Islands", "value"=>"GS"],
		["id"=>202, "text"=>"Spain", "value"=>"ES"],
		["id"=>203, "text"=>"Sri Lanka", "value"=>"LK"],
		["id"=>204, "text"=>"Sudan", "value"=>"SD"],
		["id"=>205, "text"=>"Suriname", "value"=>"SR"],
		["id"=>206, "text"=>"Svalbard and Jan Mayen", "value"=>"SJ"],
		["id"=>207, "text"=>"Swaziland", "value"=>"SZ"],
		["id"=>208, "text"=>"Sweden", "value"=>"SE"],
		["id"=>209, "text"=>"Switzerland", "value"=>"CH"],
		["id"=>210, "text"=>"Syrian Arab Republic", "value"=>"SY"],
		["id"=>211, "text"=>"Taiwan, Province of China", "value"=>"TW"],
		["id"=>212, "text"=>"Tajikistan", "value"=>"TJ"],
		["id"=>213, "text"=>"Tanzania, United Republic of", "value"=>"TZ"],
		["id"=>214, "text"=>"Thailand", "value"=>"TH"],
		["id"=>215, "text"=>"Timor-Leste", "value"=>"TL"],
		["id"=>216, "text"=>"Togo", "value"=>"TG"],
		["id"=>217, "text"=>"Tokelau", "value"=>"TK"],
		["id"=>218, "text"=>"Tonga", "value"=>"TO"],
		["id"=>219, "text"=>"Trinidad and Tobago", "value"=>"TT"],
		["id"=>220, "text"=>"Tunisia", "value"=>"TN"],
		["id"=>221, "text"=>"Turkey", "value"=>"TR"],
		["id"=>222, "text"=>"Turkmenistan", "value"=>"TM"],
		["id"=>223, "text"=>"Turks and Caicos Islands", "value"=>"TC"],
		["id"=>224, "text"=>"Tuvalu", "value"=>"TV"],
		["id"=>225, "text"=>"Uganda", "value"=>"UG"],
		["id"=>226, "text"=>"Ukraine", "value"=>"UA"],
		["id"=>227, "text"=>"United Arab Emirates", "value"=>"AE"],
		["id"=>228, "text"=>"United Kingdom", "value"=>"GB"],
		["id"=>229, "text"=>"United States", "value"=>"US"],
		["id"=>230, "text"=>"United States Minor Outlying Islands", "value"=>"UM"],
		["id"=>231, "text"=>"Uruguay", "value"=>"UY"],
		["id"=>232, "text"=>"Uzbekistan", "value"=>"UZ"],
		["id"=>233, "text"=>"Vanuatu", "value"=>"VU"],
		["id"=>234, "text"=>"Venezuela", "value"=>"VE"],
		["id"=>235, "text"=>"Viet Nam", "value"=>"VN"],
		["id"=>236, "text"=>"Virgin Islands, British", "value"=>"VG"],
		["id"=>237, "text"=>"Virgin Islands, U.S.", "value"=>"VI"],
		["id"=>238, "text"=>"Wallis and Futuna", "value"=>"WF"],
		["id"=>239, "text"=>"Western Sahara", "value"=>"EH"],
		["id"=>240, "text"=>"Yemen", "value"=>"YE"],
		["id"=>241, "text"=>"Zambia", "value"=>"ZM"],
		["id"=>242, "text"=>"Zimbabwe", "value"=>"ZW"]
];

	header("Content-Type: application/json");
	echo json_encode($countries);
//print_r( $countries );
